set(_CATKIN_CURRENT_PACKAGE "transform_hw")
set(transform_hw_VERSION "0.0.0")
set(transform_hw_MAINTAINER "justin <justin@todo.todo>")
set(transform_hw_PACKAGE_FORMAT "2")
set(transform_hw_BUILD_DEPENDS "geometry_msgs" "roscpp" "tf2" "tf2_ros")
set(transform_hw_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "tf2" "tf2_ros")
set(transform_hw_BUILDTOOL_DEPENDS "catkin")
set(transform_hw_BUILDTOOL_EXPORT_DEPENDS )
set(transform_hw_EXEC_DEPENDS "geometry_msgs" "roscpp" "tf2" "tf2_ros")
set(transform_hw_RUN_DEPENDS "geometry_msgs" "roscpp" "tf2" "tf2_ros")
set(transform_hw_TEST_DEPENDS )
set(transform_hw_DOC_DEPENDS )
set(transform_hw_URL_WEBSITE "")
set(transform_hw_URL_BUGTRACKER "")
set(transform_hw_URL_REPOSITORY "")
set(transform_hw_DEPRECATED "")